swagger: '2.0'
info:
  title: jmdictgateway
  description: Sample API on API Gateway with a Cloud Run backend
  version: 1.0.0
schemes:
- https
produces:
- application/json

x-google-backend:
  address: https://jmdict-gql-zo3qquyvrq-ew.a.run.app

securityDefinitions:
  api_key:
    type: apiKey
    name: x-api-key
    in: header

# Add CORS support
x-google-endpoints:
- name: jmdict-gql-zo3qquyvrq-ew.a.run.app
  allowCors: true  # Enable CORS

paths:
  /hello:
    get:
      summary: Greet a user
      operationId: hello
      x-google-backend:
        address: https://jmdict-gql-zo3qquyvrq-ew.a.run.app
      security:
        - api_key: []
      responses:
        '200':
          description: A successful response
          schema:
            type: string

  /gql:
    post:
      summary: GraphQL Endpoint
      operationId: graphqlPost
      x-google-backend:
        address: https://jmdict-gql-zo3qquyvrq-ew.a.run.app/gql
      consumes:
        - application/json
      parameters:
        - name: body
          in: body
          description: GraphQL query
          required: true
          schema:
            type: object
            properties:
              query:
                type: string
              variables:
                type: object
      security:
        - api_key: []
      responses:
        '200':
          description: A successful response
          schema:
            type: object

    options:
      summary: CORS preflight
      operationId: graphqlOptions
      x-google-backend:
        address: https://jmdict-gql-zo3qquyvrq-ew.a.run.app/gql
      consumes:
        - application/json
      responses:
        '204':
          description: No Content - CORS preflight request successful
      x-google-extensions:
        - x-google-cors:
            allowMethods: "POST, OPTIONS"
            allowHeaders: "Content-Type, x-api-key"
            allowOrigin: "*"
